### ISSUE TITLE
Getting crashes

### ISSUE THREAD

**Issue by elgatito** [anacrolix/go-libutp#6]
Getting crashes, coming from libutp, looks like connectivity problem is causing it.

Here is the log part.

```

07:51:14.868 T:140043090876160  NOTICE: [plugin.video.elementum] elementum: /ext-go/2/src/github.com/anacrolix/go-libutp/utp_internal.cpp:3314: int utp_getpeername(utp_socket*, sockaddr*, socklen_t*): Assertion `conn' failed.
07:51:15.874 T:140043090876160  NOTICE: [plugin.video.elementum]
07:51:15.874 T:140043090876160  NOTICE: [plugin.video.elementum] PC=0x7fc0019d90bb m=7 sigcode=18446744073709551610
07:51:15.875 T:140043090876160  NOTICE: [plugin.video.elementum] signal arrived during cgo execution
07:51:15.875 T:140043090876160  NOTICE: [plugin.video.elementum]
07:51:15.876 T:140043090876160  NOTICE: [plugin.video.elementum] goroutine 10768 [syscall, locked to thread]:
07:51:15.877 T:140043090876160  NOTICE: [plugin.video.elementum] runtime.cgocall(0xb9be00, 0xc420d62b30, 0x1)
07:51:15.877 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420d62b00 sp=0xc420d62ac0
07:51:15.878 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/go-libutp._Cfunc_utp_getpeername(0x0, 0xc421148cb0, 0xc4203c0f38, 0x0)
07:51:15.878 T:140043090876160  NOTICE: [plugin.video.elementum] 	github.com/anacrolix/go-libutp/_obj/_cgo_gotypes.go:294 +0x4d fp=0xc420d62b30 sp=0xc420d62b00
07:51:15.882 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/go-libutp.(*Conn).RemoteAddr.func1(0x0, 0xc421148cb0, 0xc4203c0f38, 0xd0eae0)
07:51:15.883 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/go-libutp/conn.go:196 +0x74 fp=0xc420d62b68 sp=0xc420d62b30
07:51:15.883 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/go-libutp.(*Conn).RemoteAddr(0xc42060ab40, 0x1432790, 0xc4226debd0)
07:51:15.884 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/go-libutp/conn.go:197 +0x76 fp=0xc420d62ba8 sp=0xc420d62b68
07:51:15.884 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).remoteAddr(0xc4200c7b80, 0x13, 0xc42332f620)
07:51:15.885 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/connection.go:111 +0x34 fp=0xc420d62bd0 sp=0xc420d62ba8
07:51:15.885 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Torrent).addrActive(0xc4206c7680, 0xc42332f620, 0x13, 0x5)
07:51:15.886 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/torrent.go:205 +0xdd fp=0xc420d62c70 sp=0xc420d62bd0
07:51:15.892 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).initiateConn(0xc420219880, 0x0, 0x0, 0x0, 0xc420f07234, 0x4, 0x4, 0x9fd6, 0xe37ef1, 0x1, ...)
07:51:15.893 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/client.go:513 +0x1d0 fp=0xc420d62d50 sp=0xc420d62c70
07:51:15.905 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).openNewConns(0xc420219880, 0xc4206c7680)
07:51:15.908 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/client.go:1185 +0x227 fp=0xc420d62ee0 sp=0xc420d62d50
07:51:15.909 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).noLongerHalfOpen(0xc420219880, 0xc4206c7680, 0xc422d0b6e0, 0x13)
07:51:15.910 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/client.go:598 +0xb6 fp=0xc420d62f40 sp=0xc420d62ee0
07:51:15.912 T:140043090876160  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc420219880, 0xc4206c7680, 0xc422d0b6e0, 0x13, 0xe37ef1, 0x1)
07:51:15.913 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/client.go:686 +0xdf fp=0xc420d62fb0 sp=0xc420d62f40
07:51:15.919 T:140043090876160  NOTICE: [plugin.video.elementum] runtime.goexit()
07:51:15.921 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420d62fb8 sp=0xc420d62fb0
07:51:15.921 T:140043090876160  NOTICE: [plugin.video.elementum] created by github.com/anacrolix/torrent.(*Client).initiateConn
07:51:15.922 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/2/src/github.com/anacrolix/torrent/client.go:517 +0x2d2
07:51:15.924 T:140043090876160  NOTICE: [plugin.video.elementum]
07:51:15.925 T:140043090876160  NOTICE: [plugin.video.elementum] goroutine 1 [IO wait, 1 minutes]:
07:51:15.926 T:140043090876160  NOTICE: [plugin.video.elementum] net.runtime_pollWait(0x7fc002663c00, 0x72, 0x143f1e0)
07:51:15.926 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/runtime/netpoll.go:164 +0x59
07:51:15.927 T:140043090876160  NOTICE: [plugin.video.elementum] net.(*pollDesc).wait(0xc4201ce7d8, 0x72, 0x143a010, 0xc4204132c0)
07:51:15.928 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
07:51:15.942 T:140043090876160  NOTICE: [plugin.video.elementum] net.(*pollDesc).waitRead(0xc4201ce7d8, 0xffffffffffffffff, 0x0)
07:51:15.942 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
07:51:15.942 T:140043090876160  NOTICE: [plugin.video.elementum] net.(*netFD).accept(0xc4201ce770, 0x0, 0x143d6e0, 0xc4204132c0)
07:51:15.943 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
07:51:15.943 T:140043090876160  NOTICE: [plugin.video.elementum] net.(*TCPListener).accept(0xc4201995a0, 0xc4205ce3a0, 0xd017a0, 0xffffffffffffffff)
07:51:15.944 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
07:51:15.944 T:140043090876160  NOTICE: [plugin.video.elementum] net.(*TCPListener).AcceptTCP(0xc4201995a0, 0xc4207a3cb8, 0xc4207a3cc0, 0xc4207a3cb0)
07:51:15.946 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/tcpsock.go:215 +0x49
07:51:15.946 T:140043090876160  NOTICE: [plugin.video.elementum] net/http.tcpKeepAliveListener.Accept(0xc4201995a0, 0xe676a0, 0xc4205ce320, 0x14441e0, 0xc420559380)
07:51:15.947 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/http/server.go:3044 +0x2f
07:51:15.955 T:140043090876160  NOTICE: [plugin.video.elementum] net/http.(*Server).Serve(0xc420574210, 0x1443a60, 0xc4201995a0, 0x0, 0x0)
07:51:15.956 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/http/server.go:2643 +0x228
07:51:15.956 T:140043090876160  NOTICE: [plugin.video.elementum] net/http.(*Server).ListenAndServe(0xc420574210, 0xc420574210, 0xc4203382a6)
07:51:15.956 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/http/server.go:2585 +0xb0
07:51:15.957 T:140043090876160  NOTICE: [plugin.video.elementum] net/http.ListenAndServe(0xc4203382a6, 0x6, 0x0, 0x0, 0x5, 0xc4203382a6)
07:51:15.957 T:140043090876160  NOTICE: [plugin.video.elementum] 	/usr/local/go/src/net/http/server.go:2787 +0x7f
07:51:15.958 T:140043090876160  NOTICE: [plugin.video.elementum] main.main()
07:51:15.958 T:140043090876160  NOTICE: [plugin.video.elementum] 	/ext-go/1/src/github.com/elgatito/elementum/main.go:179 +0x9ce
07:51:15.959 T:140043090876160  NOTICE: [plugin.video.elementum]

```

**Comment by anacrolix** [comment]
Thanks for the report. Are you triggering or closing the torrent Client's utp Socket, injecting peer addresses manually, or running on a device with a heavy CPU load? The panic triggered requires very specific circumstances that should be very hard to reproduce. Nonetheless I've created some unit tests and made some changes that will at least fix the issue from go-libutp's perspective. Please give them a spin.
